#!/bin/bash

main() {
	eval "$@"
}

download() {
	local src_file="$1"
	local dist="$2"
	[ -z "$dist" ] && dist="dist"
	cat $src_file | while read src
	do
		local playlist=`echo $src | awk -F , '{print $1}'`
		local link=`echo $src | awk -F , '{print $2}'`
		echo \> playlist $playlist - link $link
		mkdir -p "$dist" "$dist/$playlist"
		youtube-dl -cix --add-metadata --download-archive "$dist/$playlist/.archive" --audio-format mp3 -o "$dist/$playlist/%(title)s.%(ext)s" "$link"
		eyed3 -A "$playlist" -G "$playlist" "$dist/$playlist"
	done
	snapdiff $dist
}

snapdiff() {
	local dist="$1"
	local ts=`date '+%F %H:%M:%S'`
	local snapshot="$dist/snapshot"
	local snapshot_old="$dist/snapshot_old"
	echo > $snapshot_old
	[ -f "$snapshot" ] && mv -f "$snapshot" "$snapshot_old"
	printf "$ts\n---\n" > "$snapshot"
	snap "$dist" >> "$snapshot"
	git diff --no-index "$snapshot_old" "$snapshot" | grep -E '^(\+[^\+]{2}|\-[^\-]{2})' > "$dist/update"
}

snap() {
	local dist="$1"
	find $dist -type f -name '*.mp3' | sed "s|^$dist/||"
}

install() {
	brew install youtube-dl eye-d3 ffmpeg
}

main $@

